openapi: 3.0.1
info:
  title: API_membres
  description: API Definition of API_membres
  version: 1.0.0
servers:
- url: http://localhost:8290/membres
paths:
  /Ajout_membres:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /{qr}:
    get:
      parameters:
      - name: qr
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
